### ISSUE TITLE
İs this some version of DroidDetective?

### ISSUE THREAD

**Issue by ahsentekd** [EyupErgin/DroidDetective#1]
hi, i recently reviewed your repo and have a question about it. r you planning to create new versions of this repository or is the content diverging into separate projects? https://github.com/user1342/DroidDetective

**Comment by EyupErgin** [comment]
Hello, it is obvious that there is a name similarity with the related tool, but both projects are independent of each other in most aspects.

As for your question, the DroidDetective tool is a different tool. While the tool in the link you forwarded determines whether a file is malware based on ML, the tool I created was created through the AndroGuard library to help in the static analysis of the APK file so that the necessary information can be easily obtained during the analysis phase.

I don't have any plans to evolve it into a tool similar to the tool in the link you provided.
